### ISSUE TITLE
Backend database setup

### ISSUE THREAD

**Issue by dcl10** [uon-drs/improved-octo-giggle#1]
## Description
Set up the database connection for the API following [this tutorial](https://fastapi.tiangolo.com/tutorial/sql-databases/#create-model-attributescolumns).

## Tasks
- [x] install sqlalchemy, if not already installed
- [x] add database URL
- [x] add the engine (use a sqlite DB)
- [x] Create `SessionLocal` class
- [x] Create the base class
