### ISSUE TITLE
Endpoint for getting valid checks for the frontend

### ISSUE THREAD

**Issue by dcl10** [uon-drs/improved-octo-giggle#2]
## Description
Create an endpoint that returns the valid pendera checks. The checks returned should be different depending on the type.

## Tasks
- [x] create a `GET` endpoint that returns the valid checks
- [x] use a parameter for the dtype, which will determine what to send back.
  - [x] numeric should allow <, >, <=, >= and ==  
- [x] return a list of checks

**Comment by kuraisle** [comment]
Closed with #27
