### ISSUE TITLE
Endpoint for saving a schema

### ISSUE THREAD

**Issue by dcl10** [uon-drs/improved-octo-giggle#7]
## Description
This endpoint should receive a JSON object that represents a pandera schema and save that schema to the database.

## Tasks
- [x] A class that will represent a schema to be stored in the database
- [x] An endpoint that accepts `POST` requests
- [x] A service that takes the received json, converts it to the schema class and saves it to the database
