### ISSUE TITLE
Form for validating a dataset against a schema

### ISSUE THREAD

**Issue by dcl10** [uon-drs/improved-octo-giggle#8]
## Description
Create a form which the user selects an available schema and uploads a file to validate against that schema.

## Tasks
- [x] Retrieve available schemas to add to a select box
- [x] Add endpoint to backend for getting available schemas
- [ ] Submit for file to the backend
- [x] Show if the file is valid under the selected schema

**Comment by kuraisle** [comment]
Task 2 (Add endpoint to backend for getting available schemas) is covered in the /schemas endpoint if you leave the request body empty - I think
